#!/bin/bash

# generate-agent-docs.sh
# Auto-generate agent-specific docs (CLAUDE.md, GEMINI.md, etc.) from AGENTS.md
# Uses actual LLM CLI tools to generate optimized documentation for each agent

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Parse arguments
PROJECT_PATH="."
AGENT=""
ALL_AGENTS=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --project)
      PROJECT_PATH="$2"
      shift 2
      ;;
    --agent)
      AGENT="$2"
      shift 2
      ;;
    --all)
      ALL_AGENTS=true
      shift
      ;;
    *)
      echo "Unknown option: $1"
      echo "Usage: $0 [--project PATH] [--agent claude|gemini|cursor] [--all]"
      exit 1
      ;;
  esac
done

if [ ! -d "$PROJECT_PATH" ]; then
  echo -e "${RED}✗ Project directory not found: $PROJECT_PATH${NC}"
  exit 1
fi

AGENTS_FILE="$PROJECT_PATH/AGENTS.md"

if [ ! -f "$AGENTS_FILE" ]; then
  echo -e "${RED}✗ AGENTS.md not found in project${NC}"
  exit 1
fi

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  Generating Agent-Specific Documentation via CLI${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Get script directory for prompt templates
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROMPT_DIR="$SCRIPT_DIR/../templates/prompts"

# Ensure prompt templates directory exists
mkdir -p "$PROMPT_DIR"

# Generate CLAUDE.md using Claude CLI
generate_claude_md() {
  echo -e "${BLUE}Generating CLAUDE.md via Claude CLI...${NC}"

  local OUTPUT="$PROJECT_PATH/CLAUDE.md"
  local PROMPT="$PROMPT_DIR/generate-claude-md.txt"

  # Create prompt template if it doesn't exist
  if [ ! -f "$PROMPT" ]; then
    cat > "$PROMPT" << 'EOF'
You are tasked with generating CLAUDE.md from AGENTS.md for a project.

CLAUDE.md should be optimized for Claude AI by:
1. Reorganizing content from AGENTS.md for Claude's strengths (long context, complex reasoning)
2. Adding Claude-specific optimizations and tips
3. Keeping the structure clear and token-efficient

Read the AGENTS.md file and generate CLAUDE.md with the following structure:

---
# CLAUDE.md

> **Claude Entry Point** | Auto-generated from [AGENTS.md](AGENTS.md)

<!-- AUTO-GENERATED: This file is automatically generated from AGENTS.md -->
<!-- To regenerate: Run scripts/generate-agent-docs.sh --agent claude -->

## Standard Policy

**MUST READ**: [AGENTS.md](AGENTS.md) - Multi-LLM Standard Policy (SSOT)

This file is optimized for **Claude** by reorganizing content from AGENTS.md.

---

## Claude-Specific Optimizations

| Feature         | Optimization                                        |
| --------------- | --------------------------------------------------- |
| Context Window  | 200K tokens - Can process long files in one go     |
| Code Generation | Artifacts support, prefers complete file output    |
| Reasoning       | Chain-of-thought reasoning natural                 |
| Token Budget    | 128k context allocation recommended                |
| Strength        | Complex reasoning, architectural decisions         |

---

## Quick Start

[Extract and reorganize Quick Start section from AGENTS.md]

## Development Methodology

[Extract and reorganize methodology sections from AGENTS.md]
[Add Claude-specific tips for each methodology (CDD, SDD, ADD)]

## CDD Rules

[Extract CDD rules and add Claude-specific optimizations]

## Essential Reading

[Extract essential reading list]

## Directory Structure

[Extract and present directory structure clearly]

## Project-Specific Configuration

[Extract PROJECT CUSTOM section from AGENTS.md]

---

**Generated from**: AGENTS.md
**Last Updated**: [current date]
**Claude Version Optimized**: Claude 3.5 Sonnet, Claude 3 Opus
---

Generate the complete CLAUDE.md file following this structure, extracting and reorganizing content from the provided AGENTS.md.
EOF
  fi

  # Check if claude CLI is available
  if command -v claude &> /dev/null; then
    echo -e "  Using: ${GREEN}claude${NC} CLI"

    # Read AGENTS.md and pass to Claude
    cat "$AGENTS_FILE" | claude --prompt "$(cat "$PROMPT")" > "$OUTPUT" 2>/dev/null && \
      echo -e "${GREEN}✓ Generated: CLAUDE.md${NC}" || \
      echo -e "${YELLOW}⚠ Claude CLI failed, using fallback${NC}"
  else
    echo -e "  ${YELLOW}⚠ Claude CLI not found, using fallback generation${NC}"
    generate_claude_md_fallback
  fi
}

# Generate GEMINI.md using Gemini CLI
generate_gemini_md() {
  echo -e "${BLUE}Generating GEMINI.md via Gemini CLI...${NC}"

  local OUTPUT="$PROJECT_PATH/GEMINI.md"
  local PROMPT="$PROMPT_DIR/generate-gemini-md.txt"

  # Create prompt template if it doesn't exist
  if [ ! -f "$PROMPT" ]; then
    cat > "$PROMPT" << 'EOF'
You are tasked with generating GEMINI.md from AGENTS.md for a project.

GEMINI.md should be optimized for Gemini AI by:
1. Reorganizing content from AGENTS.md for Gemini's strengths (1M+ context, multimodal, fast iteration)
2. Adding Gemini-specific optimizations and tips
3. Using compact, table-heavy format for speed

Read the AGENTS.md file and generate GEMINI.md with the following structure:

---
# GEMINI.md

> **Gemini Entry Point** | Auto-generated from [AGENTS.md](AGENTS.md)

<!-- AUTO-GENERATED: This file is automatically generated from AGENTS.md -->
<!-- To regenerate: Run scripts/generate-agent-docs.sh --agent gemini -->

## Standard Policy

**MUST READ**: [AGENTS.md](AGENTS.md) - Multi-LLM Standard Policy (SSOT)

This file is optimized for **Gemini** by reorganizing content from AGENTS.md.

---

## Gemini-Specific Optimizations

| Feature        | Optimization                                         |
| -------------- | ---------------------------------------------------- |
| Context Window | 1M+ tokens - Can process entire codebase at once    |
| Multimodal     | Supports images, diagrams, screenshots              |
| Speed          | Fast response, ideal for rapid iteration            |
| Batch Mode     | Efficient for bulk documentation generation         |
| Strength       | Broad knowledge, fast prototyping, batch processing |

---

## Quick Start (Compact)

[Extract and make compact for speed]

## Methodology Summary

[Extract methodology as compact tables]

## Rules (Gemini-Optimized)

[Extract rules with Gemini-specific tips]

## Directory Structure (Quick Ref)

[Compact representation]

## Project-Specific Configuration

[Extract PROJECT CUSTOM section]

---

**Generated from**: AGENTS.md
**Last Updated**: [current date]
**Gemini Version Optimized**: Gemini 1.5 Pro, Gemini 2.0 Flash
---

Generate the complete GEMINI.md file following this structure, making it compact and table-heavy for Gemini's fast processing.
EOF
  fi

  # Check if gemini CLI is available
  if command -v gemini &> /dev/null || command -v aistudio &> /dev/null; then
    local GEMINI_CMD=$(command -v gemini || command -v aistudio)
    echo -e "  Using: ${GREEN}$GEMINI_CMD${NC} CLI"

    cat "$AGENTS_FILE" | $GEMINI_CMD "$(cat "$PROMPT")" > "$OUTPUT" 2>/dev/null && \
      echo -e "${GREEN}✓ Generated: GEMINI.md${NC}" || \
      echo -e "${YELLOW}⚠ Gemini CLI failed, using fallback${NC}"
  else
    echo -e "  ${YELLOW}⚠ Gemini CLI not found, using fallback generation${NC}"
    generate_gemini_md_fallback
  fi
}

# Generate CURSOR.md using Cursor CLI
generate_cursor_md() {
  echo -e "${BLUE}Generating CURSOR.md via Cursor CLI...${NC}"

  local OUTPUT="$PROJECT_PATH/CURSOR.md"
  local PROMPT="$PROMPT_DIR/generate-cursor-md.txt"

  # Create prompt template
  if [ ! -f "$PROMPT" ]; then
    cat > "$PROMPT" << 'EOF'
You are tasked with generating CURSOR.md from AGENTS.md for a project.

CURSOR.md should be optimized for Cursor IDE by:
1. Reorganizing content from AGENTS.md for Cursor's strengths (IDE integration, inline edits)
2. Adding Cursor-specific shortcuts and workflow tips
3. Emphasizing file-based context and workspace awareness

Read the AGENTS.md file and generate CURSOR.md focused on Cursor IDE workflow.

[Similar structure to CLAUDE.md and GEMINI.md, but optimized for Cursor]
EOF
  fi

  # Note: Cursor CLI doesn't have a direct command-line tool
  # Use fallback generation
  echo -e "  ${YELLOW}⚠ Cursor CLI not available, using fallback generation${NC}"
  generate_cursor_md_fallback
}

# Fallback generators (use sed/awk to reorganize AGENTS.md)
generate_claude_md_fallback() {
  local OUTPUT="$PROJECT_PATH/CLAUDE.md"

  cat > "$OUTPUT" << 'EOFMARKER'
# CLAUDE.md

> **Claude Entry Point** | Auto-generated from [AGENTS.md](AGENTS.md)

<!-- AUTO-GENERATED: See AGENTS.md for source -->
<!-- To regenerate: Run scripts/generate-agent-docs.sh --agent claude -->

## ⚠️ Fallback Version

This file was generated using fallback mode (Claude CLI not available).

For optimal Claude-specific optimizations, install Claude CLI and regenerate.

---

## Quick Reference

**Read**: [AGENTS.md](AGENTS.md) for complete standard policy.

**Claude Strengths**:
- Long context (200K tokens)
- Complex reasoning
- Artifacts for code generation

**Essential Files** (read first):
1. `.ai/rules.md`
2. `.ai/best-practices.md`
3. `.ai/architecture.md`

**Methodology**:
- CDD: `.ai/` (Tier 1), `docs/llm/` (Tier 2)
- SDD: `.specs/` (roadmap → scopes → tasks)
- ADD: Multi-agent execution with consensus

**Full Details**: See [AGENTS.md](AGENTS.md)

---

**Generated**: Fallback mode | **Source**: AGENTS.md
EOFMARKER

  echo -e "${YELLOW}⚠ Generated fallback CLAUDE.md${NC}"
}

generate_gemini_md_fallback() {
  local OUTPUT="$PROJECT_PATH/GEMINI.md"

  cat > "$OUTPUT" << 'EOFMARKER'
# GEMINI.md

> **Gemini Entry Point** | Auto-generated from [AGENTS.md](AGENTS.md)

<!-- AUTO-GENERATED: See AGENTS.md for source -->
<!-- To regenerate: Run scripts/generate-agent-docs.sh --agent gemini -->

## ⚠️ Fallback Version

This file was generated using fallback mode (Gemini CLI not available).

For optimal Gemini-specific optimizations, install Gemini CLI and regenerate.

---

## Quick Reference

**Read**: [AGENTS.md](AGENTS.md) for complete standard policy.

**Gemini Strengths**:
- Large context (1M+ tokens)
- Multimodal (images, diagrams)
- Fast iteration

**Essential**: `.ai/rules.md`, `.ai/best-practices.md`, `.ai/architecture.md`

**Methodology**: CDD (4-tier), SDD (3-layer), ADD (multi-agent)

**Full Details**: See [AGENTS.md](AGENTS.md)

---

**Generated**: Fallback mode | **Source**: AGENTS.md
EOFMARKER

  echo -e "${YELLOW}⚠ Generated fallback GEMINI.md${NC}"
}

generate_cursor_md_fallback() {
  local OUTPUT="$PROJECT_PATH/CURSOR.md"

  cat > "$OUTPUT" << 'EOFMARKER'
# CURSOR.md

> **Cursor Entry Point** | Auto-generated from [AGENTS.md](AGENTS.md)

<!-- AUTO-GENERATED: See AGENTS.md for source -->
<!-- To regenerate: Run scripts/generate-agent-docs.sh --agent cursor -->

## ⚠️ Fallback Version

This file was generated using fallback mode.

---

## Quick Reference for Cursor

**Read**: [AGENTS.md](AGENTS.md) for complete standard policy.

**Cursor Workflow**:
- Cmd+K: Inline edits
- Cmd+L: Chat
- @file: Reference specific files
- @codebase: Search entire project

**Keep Open**: `.ai/rules.md`, `.ai/architecture.md`, current task file

**Full Details**: See [AGENTS.md](AGENTS.md)

---

**Generated**: Fallback mode | **Source**: AGENTS.md
EOFMARKER

  echo -e "${YELLOW}⚠ Generated fallback CURSOR.md${NC}"
}

# Execute generation
if [ "$ALL_AGENTS" = true ]; then
  generate_claude_md
  generate_gemini_md
  generate_cursor_md
elif [ -n "$AGENT" ]; then
  case "$AGENT" in
    claude)
      generate_claude_md
      ;;
    gemini)
      generate_gemini_md
      ;;
    cursor)
      generate_cursor_md
      ;;
    *)
      echo -e "${RED}✗ Unknown agent: $AGENT${NC}"
      echo "Supported: claude, gemini, cursor"
      exit 1
      ;;
  esac
else
  # Default: generate all
  generate_claude_md
  generate_gemini_md
  generate_cursor_md
fi

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✓ Agent documentation generation complete${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Note: These files are auto-generated. To update, edit AGENTS.md and re-run this script."
echo "For best results, ensure Claude/Gemini CLI tools are installed."

exit 0
